/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './view/__root'
import { Route as privateLayoutRouteImport } from './view/(private)/layout'
import { Route as privateIndexRouteImport } from './view/(private)/index'

const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof privateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof privateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(private)/': typeof privateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(private)' | '/(private)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
  }
}

interface privateLayoutRouteChildren {
  privateIndexRoute: typeof privateIndexRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateIndexRoute: privateIndexRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateLayoutRoute: privateLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
