/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './view/__root'
import { Route as publicLayoutRouteImport } from './view/(public)/layout'
import { Route as privateLayoutRouteImport } from './view/(private)/layout'
import { Route as privateIndexRouteImport } from './view/(private)/index'
import { Route as publicLoginIndexRouteImport } from './view/(public)/login/index'
import { Route as privateJogosIndexRouteImport } from './view/(private)/jogos/index'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateIndexRoute = privateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const publicLoginIndexRoute = publicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => publicLayoutRoute,
} as any)
const privateJogosIndexRoute = privateJogosIndexRouteImport.update({
  id: '/jogos/',
  path: '/jogos/',
  getParentRoute: () => privateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof privateIndexRoute
  '/jogos/': typeof privateJogosIndexRoute
  '/login/': typeof publicLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof privateIndexRoute
  '/jogos': typeof privateJogosIndexRoute
  '/login': typeof publicLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(public)': typeof publicLayoutRouteWithChildren
  '/(private)/': typeof privateIndexRoute
  '/(private)/jogos/': typeof privateJogosIndexRoute
  '/(public)/login/': typeof publicLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jogos/' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jogos' | '/login'
  id:
    | '__root__'
    | '/(private)'
    | '/(public)'
    | '/(private)/'
    | '/(private)/jogos/'
    | '/(public)/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(public)/login/': {
      id: '/(public)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof publicLoginIndexRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(private)/jogos/': {
      id: '/(private)/jogos/'
      path: '/jogos'
      fullPath: '/jogos/'
      preLoaderRoute: typeof privateJogosIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
  }
}

interface privateLayoutRouteChildren {
  privateIndexRoute: typeof privateIndexRoute
  privateJogosIndexRoute: typeof privateJogosIndexRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateIndexRoute: privateIndexRoute,
  privateJogosIndexRoute: privateJogosIndexRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

interface publicLayoutRouteChildren {
  publicLoginIndexRoute: typeof publicLoginIndexRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicLoginIndexRoute: publicLoginIndexRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateLayoutRoute: privateLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
